# vim-style keys for pane navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# pane splitting shortcuts
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# start numbering from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# mouse support
set -g mouse on
set -g set-clipboard on

# remove delay after prefix
set -sg escape-time 0

# reload config quickly
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Use vim keybindings in copy mode
setw -g mode-keys vi

# Remap 'v' to start selection (like Vim)
bind -T copy-mode-vi v send -X begin-selection

# Remap 'y' to copy (yank) selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# This helps sync tmux buffer with system clipboard
set -g set-clipboard on

# COLORS
# base status bar
set -g status-style bg=#1e1e2e,fg=#cdd6f4

# active window (light purple highlight)
setw -g window-status-current-style fg=#1e1e2e,bg=#cba6f7

# inactive windows
setw -g window-status-style fg=#6c7086,bg=#1e1e2e

# left (session name)
set -g status-left "#[fg=#cba6f7]#S "

# right (date + time with contrast)
set -g status-right "#[fg=#89dceb]%Y-%m-%d #[fg=#74c7ec]%H:%M "

set -g mode-style "bg=#cba6f7,fg=#1e1e2e"
